### ISSUE TITLE
Possible cookie consent

### ISSUE THREAD

**Issue by Chalarangelo** [30-seconds/30-seconds-starter#3]
We might want to develop a cookie policy and/or use a gatsby plugin to handle analytics and cookies, so that users are informed and we are GDPR-compliant.

[`gatsby-plugin-cookiehub`](https://www.gatsbyjs.org/packages/gatsby-plugin-cookiehub/?=gdpr) seems like a good option, but it's not very customizable and there are limitations to its API. I also can't figure out how to set it up properly, as I don't know which is my Widget ID.

[tarteaucitron](https://opt-out.ferank.eu/en/) is another option, known to be GDPR-compliant and would probably be my first choice. However, setting it up with gatsby has proven very difficult.

If anyone wants to help out, please feel free to do so. I kinda need some help with this. It's not top priority, but it's certainly important that we implement this.

As it stands now, the only tracking we have is Google Analytics, which is opt-in per repository and is not very intrusive, due to the default configuration I have provided. In theory, it should not cause any trouble with the GDPR in Europe, but we should be careful about these matters.

**Comment by skatcat31** [comment]
https://github.com/osano/cookieconsent is an opensource, free, JS utility for it. How are we allowing them to opt out? Standard set a cookie that gets checked before firing a tracking request?

**Comment by Chalarangelo** [comment]
I'm closing the issue as the starter template is now archived. We will soon provide additional tools and information to resolve any remaining issues.
